Q1:  Write a program to create numpy array or vector of all the even integers from 20 to 50 exluding 20 and 50.

In [4]:
import numpy as np
arr = np.arange(22,50,2)
print(arr)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48]


2. Create a multi-dimensional array of 3 rows and 3 columns having odd numbers from 1 to 19 including 1 and excluding 19. After that, iterate over this array to print all elements.

In [5]:
arr = np.arange(1,19,2).reshape(3,3)
for i in np.nditer(arr):
    print(i,end=" ")

1 3 5 7 9 11 13 15 17 

3. Create 3x3 matrix containing only even numbers. Multiply each element of this array with 4 and then multiply resultant matrix with 3x3 identity matrix (identity matrix should not be hardcoded).

In [6]:
identity_matrix = np.eye(3)
even_array = np.arange(2,20,2).reshape(3,3)
even_array = 4*even_array
result = even_array * identity_matrix
print(result)

[[ 8.  0.  0.]
 [ 0. 40.  0.]
 [ 0.  0. 72.]]


4. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

In [21]:
datatype = [('name', 'S20'), ('height', float), ('class', int)]

array = np.array([
    ('Alice', 5.5, '10'),
    ('Bob', 5.8, '10'),
    ('Charlie', 5.6, '10'),
    ('David', 5.9, '10'),
    ('Eve', 5.5, '10')
], dtype=datatype)
print(arr)

sorted_array = np.sort(array, order=['class', 'height'])
print(sorted_array)

[3.19557165e-01 6.94877699e-01 6.72686307e-01 1.64149260e-01
 8.63924273e-01 2.83584746e-01 1.69926274e-01 3.41425811e-01
 8.52390269e-01 3.29195412e-01 1.96455083e-01 7.71499608e-01
 8.48735707e-01 1.74057475e-01 8.54631211e-01 6.73903501e-01
 3.64516175e-01 1.41507252e-01 7.76066234e-01 7.50116596e-02
 6.48886447e-01 3.82731211e-01 8.15792379e-01 9.38495889e-01
 7.40768451e-01 5.01347346e-01 8.88839466e-02 3.99842366e-01
 2.82092712e-01 3.02986706e-01 6.82789520e-02 7.22103813e-01
 4.13952842e-01 5.92581658e-01 4.48861201e-01 6.03968609e-01
 2.72807954e-01 1.63226384e-01 4.84011399e-01 5.58845791e-02
 2.07223909e-01 5.72025914e-01 3.20622181e-01 8.20498660e-02
 8.80477113e-01 4.05737602e-02 5.13127783e-01 3.83243866e-01
 9.15112100e-01 8.07444870e-01 7.07991355e-01 5.22745280e-03
 8.34171296e-01 9.10776703e-01 7.76956259e-01 6.12255294e-01
 5.01998596e-02 7.42019306e-01 6.83047321e-01 6.27753391e-01
 9.31682632e-01 3.82605573e-01 2.01744256e-01 4.78235294e-01
 4.21544933e-01 1.018921

5. Generate 4x4 matrix with random numbers only from (2,5,9,10) and then multiply this matrix with identity matrix. Finally add this matrix to any 4x4 matrix having only odd numbers.

In [7]:
random_numbers = np.random.choice([2,5,9,10],size=(4,4))
identity_matrix = np.eye(4)
result = random_numbers * identity_matrix
odd_array = np.arange(1,32,2).reshape(4,4)
result = result + odd_array
print(result)

[[ 3.  3.  5.  7.]
 [ 9. 16. 13. 15.]
 [17. 19. 23. 23.]
 [25. 27. 29. 33.]]


6. Write a NumPy program to multiply a 5x3 matrix by a 3x2.

In [14]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
result = np.matmul(arr1,arr2)
print(result)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


7. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements. Save all the results in text file created at runtime.

In [17]:
arr = np.random.rand(1000)
avg = arr.mean()
var = arr.var()
std = arr.std()

with open('results.txt', 'w') as f:
    f.write(f"Average: {avg}\n")
    f.write(f"Variance: {var}\n")
    f.write(f"Standard Deviation: {std}")